// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box: typeof import('./src/components/common/Box.vue')['default']
    BrowserAddressBar: typeof import('./src/components/Browser/BrowserAddressBar.vue')['default']
    BrowserAddressDropdown: typeof import('./src/components/Browser/BrowserAddressDropdown.vue')['default']
    BrowserAddressDropdownItem: typeof import('./src/components/Browser/BrowserAddressDropdownItem.vue')['default']
    BrowserAddressMedia: typeof import('./src/components/Browser/BrowserAddressMedia.vue')['default']
    BrowserContent: typeof import('./src/components/Browser/BrowserContent.vue')['default']
    BrowserView: typeof import('./src/components/Browser/BrowserView.vue')['default']
    ComponentsMenu: typeof import('./src/components/Menu/ComponentsMenu.vue')['default']
    ComponentsMenuItem: typeof import('./src/components/Menu/ComponentsMenuItem.vue')['default']
    ComponentsMenuSubItem: typeof import('./src/components/Menu/ComponentsMenuSubItem.vue')['default']
    FieldSave: typeof import('./src/components/common/FieldSave.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeNode: typeof import('./src/components/common/TreeNode.vue')['default']
    VFrame: typeof import('./src/components/common/VFrame.vue')['default']
  }
}

export {}
