// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box: typeof import('./components/common/Box.vue')['default']
    BrowserAddressBar: typeof import('./components/Browser/BrowserAddressBar.vue')['default']
    BrowserAddressDropdown: typeof import('./components/Browser/BrowserAddressDropdown.vue')['default']
    BrowserAddressDropdownItem: typeof import('./components/Browser/BrowserAddressDropdownItem.vue')['default']
    BrowserAddressMedia: typeof import('./components/Browser/BrowserAddressMedia.vue')['default']
    BrowserContent: typeof import('./components/Browser/BrowserContent.vue')['default']
    BrowserView: typeof import('./components/Browser/BrowserView.vue')['default']
    ComponentsMenu: typeof import('./components/ComponentsMenu.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FieldSave: typeof import('./components/common/FieldSave.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
